In [1]:
import numpy as np

In [2]:
arr = np.random.randn(5,4)

In [4]:
arr.sum() # elementlar yeg'indisi

-8.270384031804113

In [5]:
np.sum(arr) # elementlar yeg'indisi'

-8.270384031804113

In [7]:
arr.sum(axis=1) # qator bo'yicha yeg'indi

array([-0.84050582, -1.46531356, -2.54967263,  1.08439131, -4.49928333])

In [8]:
arr.sum(axis=0) # ustun

array([-2.77138903, -4.20938623, -1.45852656,  0.16891778])

In [9]:
# mean metodi --> o'rta arifmetik

In [10]:
data = np.arange(5)

In [11]:
np.mean(data)

2.0

In [12]:
data.mean()

2.0

In [13]:
arr

array([[-0.32627616, -0.50565556,  0.99853897, -1.00711307],
       [-0.90092126, -0.28106928, -0.90877814,  0.62545513],
       [-1.74627337, -1.28768521, -0.01606199,  0.50034794],
       [ 1.7282142 , -0.06865227, -1.41228179,  0.83711117],
       [-1.52613243, -2.06632391, -0.11994361, -0.78688338]])

In [15]:
np.mean(arr) # arrayning o'rtacha qiymati

-0.41351920159020567

In [16]:
np.mean(arr, axis=1) # qator boyicha ortacha qiymat

array([-0.21012646, -0.36632839, -0.63741816,  0.27109783, -1.12482083])

In [17]:
arr.mean(axis=0) # ustunlar bo'yicha ortacha qiymat

array([-0.55427781, -0.84187725, -0.29170531,  0.03378356])

In [19]:
# cumsum metodi

In [21]:
data

array([0, 1, 2, 3, 4])

In [23]:
result = data.cumsum() #
print(result)

[ 0  1  3  6 10]
