In [1]:
import numpy as np

In [6]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6,12).reshape(2,3)

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
arr1 * arr2

array([[ 0,  7, 16],
       [27, 40, 55]])

In [9]:
arr2/arr1

/tmp/ipykernel_5920/3928394685.py:1: RuntimeWarning: divide by zero encountered in divide
  arr2/arr1


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [10]:
arr1 + arr2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [11]:
arr2 - arr1

array([[6, 6, 6],
       [6, 6, 6]])

In [12]:
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [13]:
arr2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])