In [1]:
import numpy as np

In [2]:
# Sorting

In [6]:
arr = np.random.randn(10)

In [10]:
arr

array([ 0.31050181, -0.21947404,  0.79354414,  0.68135198, -0.23285077,
        0.57625561, -0.63438477, -2.48557339, -0.32870083, -1.26774774])

In [8]:
sorted_ar = np.sort(arr)

In [9]:
sorted_ar

array([-2.48557339, -1.26774774, -0.63438477, -0.32870083, -0.23285077,
       -0.21947404,  0.31050181,  0.57625561,  0.68135198,  0.79354414])

In [12]:
arr.sort()

In [13]:
arr

array([-2.48557339, -1.26774774, -0.63438477, -0.32870083, -0.23285077,
       -0.21947404,  0.31050181,  0.57625561,  0.68135198,  0.79354414])

In [14]:
# teskari tartiblash

In [15]:
rev_arr = -np.sort(arr)
rev_arr

array([ 2.48557339,  1.26774774,  0.63438477,  0.32870083,  0.23285077,
        0.21947404, -0.31050181, -0.57625561, -0.68135198, -0.79354414])

In [16]:
arr2d = np.random.randn(2,4)

In [17]:
arr2d

array([[ 0.95184451, -0.24084051,  0.03258916,  0.56702299],
       [-0.95917092,  0.7611327 , -0.82253561,  1.11872021]])

In [19]:
arr2d.ndim

2

In [21]:
row_sort = np.sort(arr2d, axis=0)
row_sort

array([[-0.95917092, -0.24084051, -0.82253561,  0.56702299],
       [ 0.95184451,  0.7611327 ,  0.03258916,  1.11872021]])

In [23]:
col_sort = np.sort(arr2d, axis=1)
col_sort

array([[-0.24084051,  0.03258916,  0.56702299,  0.95184451],
       [-0.95917092, -0.82253561,  0.7611327 ,  1.11872021]])