In [1]:
import numpy as np

In [2]:
xarr = np.array([1,2,3,4,5])
yarr = np.array([3,4,5,6,6])

In [3]:
cond = np.array([True, False, True, True, False])

In [6]:
result = np.where(cond, xarr, yarr)
print(result)

[1 4 3 4 6]


In [7]:
arr = np.random.randn(4, 4)

In [8]:
arr

array([[ 8.03281808e-01,  7.24957430e-01, -1.56556119e-01,
        -3.62361081e-02],
       [ 5.04779906e-01,  5.78805517e-01, -5.11125625e-01,
         3.27694557e-01],
       [-4.00097557e-04, -6.85953613e-01, -1.98765144e+00,
        -1.96312744e-01],
       [ 1.30086463e+00, -1.77466823e+00,  9.59281454e-01,
        -6.73053727e-01]])

In [9]:
# where

In [10]:
results = np.where(arr<0, -2, 2)
print(results)

[[ 2  2 -2 -2]
 [ 2  2 -2  2]
 [-2 -2 -2 -2]
 [ 2 -2  2 -2]]
