In [1]:
import numpy as np

In [3]:
names = np.array(['Nurmuhammad', 'Humoyun', 'Muhammadaziz', 'Omadbek', 'Dilshod'])
names

array(['Nurmuhammad', 'Humoyun', 'Muhammadaziz', 'Omadbek', 'Dilshod'],
      dtype='<U12')

In [6]:
data = np.random.randn(5, 4)
data

array([[-0.01817892,  0.55694271, -0.47124479, -0.308545  ],
       [-0.29280172, -1.58379095, -0.93070188,  0.27682258],
       [ 0.5188173 ,  1.12815671,  0.23181137, -1.19344035],
       [ 0.86213829,  0.97172032, -1.36293774,  0.51043336],
       [-0.79042694,  0.15046324,  0.24252452, -0.06566786]])

In [7]:
names == 'Nurmuhammad'

array([ True, False, False, False, False])

In [9]:
data[names == 'Nurmuhammad']

array([[-0.01817892,  0.55694271, -0.47124479, -0.308545  ]])

In [10]:
data[names == 'Humoyun']

array([[-0.29280172, -1.58379095, -0.93070188,  0.27682258]])

In [12]:
data[names == 'Nurmuhammad', 2:]

array([[-0.47124479, -0.308545  ]])

In [13]:
data[names != 'Omadbek'] #

array([[-0.01817892,  0.55694271, -0.47124479, -0.308545  ],
       [-0.29280172, -1.58379095, -0.93070188,  0.27682258],
       [ 0.5188173 ,  1.12815671,  0.23181137, -1.19344035],
       [-0.79042694,  0.15046324,  0.24252452, -0.06566786]])

In [14]:
data[~(names == 'Omadbek')]

array([[-0.01817892,  0.55694271, -0.47124479, -0.308545  ],
       [-0.29280172, -1.58379095, -0.93070188,  0.27682258],
       [ 0.5188173 ,  1.12815671,  0.23181137, -1.19344035],
       [-0.79042694,  0.15046324,  0.24252452, -0.06566786]])

In [20]:
mask = (names == 'Omadbek') | (names == 'Nurmuhammad')

In [21]:
mask

array([ True, False, False,  True, False])

In [23]:
data[mask]

array([[-0.01817892,  0.55694271, -0.47124479, -0.308545  ],
       [ 0.86213829,  0.97172032, -1.36293774,  0.51043336]])

In [24]:
data

array([[-0.01817892,  0.55694271, -0.47124479, -0.308545  ],
       [-0.29280172, -1.58379095, -0.93070188,  0.27682258],
       [ 0.5188173 ,  1.12815671,  0.23181137, -1.19344035],
       [ 0.86213829,  0.97172032, -1.36293774,  0.51043336],
       [-0.79042694,  0.15046324,  0.24252452, -0.06566786]])

In [25]:
data[data<0] = 0
data

array([[0.        , 0.55694271, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.27682258],
       [0.5188173 , 1.12815671, 0.23181137, 0.        ],
       [0.86213829, 0.97172032, 0.        , 0.51043336],
       [0.        , 0.15046324, 0.24252452, 0.        ]])