In [1]:
import numpy as np

In [5]:
data1 = [2, 3, 4, 5, 6, 67, 75, 30] # list

In [15]:
arr1 = np.array(data1) #arr1

In [20]:
print(arr1)

[ 2  3  4  5  6 67 75 30]


In [9]:
data2 = (3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13) # tuple

In [11]:
arr2 = np.array(data2) #array

In [13]:
print(arr2)

[ 3  4  5  6  7  8  9 10 11 12 13]


In [17]:
arr1.ndim # arr1  dimension

1

In [21]:
arr2.ndim   # arr2 dimension

1

In [40]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]] # nested list
arr3 = np.array(data3) # arr3

In [42]:
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]


In [41]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
arr3.ndim # arr3 dimension

2

In [45]:
arr3.shape # rows and columns

(2, 4)

In [46]:
arr3.size

8

In [47]:
# zeros ans ones functions
arr4 = np.zeros(shape=(2, 4)) # elements 0 rows 2, columns 4

In [49]:
print(arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [52]:
arr5  = np.ones((2,4)) # elements 1, rows 2, columns 4
print(arr5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [55]:
# arange functions
arr6 = np.arange(10, 100, 10) # start, stop, step
print(arr6)

[10 20 30 40 50 60 70 80 90]


In [56]:
arr7 = np.arange(30) # 0 to 30, step 1
print(arr7)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
