In [4]:
import numpy as np

In [8]:
arr1 = np.array([1, 2, 3, 4], dtype=np.float64) #  float64
print(arr1)

[1. 2. 3. 4.]


In [12]:
arr2 = np.array([1, 2, 3], dtype = np.int32) # int32
print(arr2)

[1 2 3]


In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int32')

In [16]:
arr3 = np.array([1, 2, 3, 4, 5, 6]) # int64
print(arr3)

[1 2 3 4 5 6]


In [18]:
float_arr3 = arr3.astype(np.float64)
float_arr3.dtype

dtype('float64')

In [19]:
data = np.array([1.8, 2, 3.5, 4, 5, 6.9]) # float64
data.dtype

dtype('float64')

In [24]:
int_data = data.astype(np.int64)
print(int_data)
int_data.dtype

[1 2 3 4 5 6]


dtype('int64')