In [1]:
import numpy as np

In [8]:
arr = np.arange(10, 100, 10)
arr[-1]

90

In [11]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
arr[3:5]

array([40, 50])

In [13]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [14]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [15]:
arr1 = np.arange(1,20,3)
arr1

array([ 1,  4,  7, 10, 13, 16, 19])

In [16]:
sliced_arr2 = arr1[3:5].copy()
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [17]:
arr1

array([ 1,  4,  7, 10, 13, 16, 19])

In [18]:
arr2d = np.array([[1,2,3,4,5], [2,4,5,6,7], [3,4,6,7,8]]) # (3, 5) array
arr2d

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 6, 7],
       [3, 4, 6, 7, 8]])

In [20]:
arr2d[1, 2]

5

In [22]:
arr2d[2, 2]

6

In [24]:
s1_arr2d = arr2d[1, 2:]
s1_arr2d

array([5, 6, 7])

In [25]:
arr3d = np.array([[[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8]],

                  [[ 9, 10, 11],
                   [12, 13, 14],
                   [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [26]:
arr3d[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
arr3d[0][2, 1]

7

In [29]:
arr3d[2][2, 1:]

array([25, 26])