In [ ]:
import numpy as np

In [3]:
x = np.array([[1.,2.,3.,4.,5.], [1.,2.,3.,4.,5]])
y = np.array([[1.,2.,3.,4.,5.], [1.,2.,3.,4.,5]])

In [4]:
print(x)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


In [5]:
print(y)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


In [6]:
x+y

array([[ 2.,  4.,  6.,  8., 10.],
       [ 2.,  4.,  6.,  8., 10.]])

In [7]:
x-y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
x*5

array([[ 5., 10., 15., 20., 25.],
       [ 5., 10., 15., 20., 25.]])

In [10]:
x = np.array([[1,2,3],[4,3,4]])

In [11]:
y = np.array([[1,2], [3,4], [5,6]])

In [13]:
x.dot(y)

array([[22, 28],
       [33, 44]])

In [14]:
np.dot(y, x)

array([[ 9,  8, 11],
       [19, 18, 25],
       [29, 28, 39]])

In [ ]:
from numpy.linalg import