In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.save('data', arr)

In [6]:
arr2 = np.load('data.npy')
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
array = np.arange(20)
np.savez('arrays', a=arr, b=array)

In [8]:
arrays = np.load('arrays.npz')

In [9]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.savez_compressed('array_comp', a=arrays, b=arrays)