In [14]:
import numpy as np
import random

In [70]:
def one_dim(n):
    """ n ta elementdan tashkil topgan 1-o'lchamli massiv """
    arr = np.random.randint(0, 100, n)
    return arr
print(one_dim(5))

[50 29 17  3 73]


In [82]:
def two_dim(r, c):
    """ r ta qator, c ta ustundan tashkil topgan 2-o'lchamli massiv """
    arr = np.ones(shape = (r, c))
    return arr

print(two_dim(4,3))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
