In [1]:
import numpy as np

In [5]:
# one dimensional array
def one_dim_array(n):
    return np.arange(n)
one_dim_array(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# elements o to 9 dimension array
def nine_dim_array(n):
    return np.zeros(n).reshape(3,3)
nine_dim_array(9)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#create array and array weight
arr = np.random.rand(10000)
print(arr.nbytes) # nbytes - number of bytes used to store the data
print(arr.size)


80000
10000


In [12]:
# array elements 0 no element 6 1
vec = np.zeros(12)
vec[5] = 1

print(vec)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [19]:
# vector elements from 20 to 59
vec = np.arange(20,60)
print(vec)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


In [25]:
# create vector and replace
arr = np.arange(10)
print(arr)
rep_arr = arr[::-1]
print(rep_arr)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [27]:
# create 3x3 matrix with values from 12 to 20
def matrix_3x3():
    return np.arange(12,21).reshape(3,3)

matrix_3x3()

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [30]:
# array not o index

def arrray(n):
    return f"array {n}, index {np.nonzero(n)}"
arrray([1,2,0,0,4,0])

'array [1, 2, 0, 0, 4, 0], index (array([0, 1, 4]),)'

In [33]:
# create 2x2x2 array with random values
def random_array():
    return np.random.rand(2,2,2)
random_array()

array([[[0.66530429, 0.2128057 ],
        [0.81197826, 0.35752697]],

       [[0.74538527, 0.7334218 ],
        [0.2069767 , 0.34069726]]])

In [38]:
# create 9x9 array with random values and find min and max
arr = np.random.rand(9,9)
print(arr)
print(f"min {arr.min()}, max {arr.max()}")

[[0.58709987 0.52738272 0.89430177 0.49388055 0.20146985 0.8453943
  0.37577173 0.71206652 0.74213179]
 [0.38192924 0.56854412 0.31092657 0.29609595 0.74749394 0.53844339
  0.40017877 0.54775824 0.16145828]
 [0.27657641 0.41741623 0.21836596 0.87217359 0.36874436 0.63684935
  0.24266525 0.81455762 0.34077351]
 [0.55256075 0.86571061 0.85513727 0.60201333 0.9483651  0.13071288
  0.49007272 0.56116409 0.41343554]
 [0.49422461 0.57457052 0.99710939 0.96668434 0.27755619 0.94462372
  0.27680057 0.63371632 0.03036038]
 [0.35584466 0.21653621 0.8813089  0.65386525 0.62608687 0.30978662
  0.22423792 0.72912014 0.9882897 ]
 [0.74342185 0.43674612 0.05355056 0.6254933  0.60604729 0.17629689
  0.5095588  0.32347738 0.28667965]
 [0.92227576 0.94866834 0.41117224 0.92620421 0.60294031 0.49437303
  0.17448161 0.13658505 0.75180442]
 [0.90391608 0.19061743 0.05004642 0.42430319 0.80603945 0.7306961
  0.41993574 0.8190882  0.98245048]]
min 0.030360381070508646, max 0.9971093940771292


In [46]:
# create 6x3 and 3x4 matrix and multiply

a = [1,2,3,4,5,6]
b = [1,2,3,4,5,6,7,8,9,10,11,12]
if a>b:
    print(False, False)
if a>=b:
    print(False, False)
if a<b:
    print(True, True)
if a<=b:
    print(True, True)

True True
True True


In [41]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [47]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/4z/p7tk3ktn5bxcqwyk547j18h00000gp/T/ipykernel_2282/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/var/folders/4z/p7tk3ktn5bxcqwyk547j18h00000gp/T/ipykernel_2282/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

In [49]:
arr1 = np.random.randint(0,10,10)
print(arr1)
arr2 = np.random.randint(0,10,10)
print(arr2)
np.intersect1d(arr1,arr2)

[5 8 4 1 4 6 0 6 8 0]
[4 2 9 0 1 2 0 3 0 7]


array([0, 1, 4])

In [53]:
arr = np.random.randint(0,10,10)
floor = np.floor(arr)
asytpe = floor.astype(int)
trunc = np.trunc(arr)
print(arr)
print(floor)
print(asytpe)
print(trunc)

[9 1 3 8 1 0 8 0 5 8]
[9. 1. 3. 8. 1. 0. 8. 0. 5. 8.]
[9 1 3 8 1 0 8 0 5 8]
[9. 1. 3. 8. 1. 0. 8. 0. 5. 8.]


In [55]:
# array column 0 to 2
def array_column():
    arr = np.random.randint(0,10,10).reshape(2,5)
    return arr[:,0:2]

array_column()


array([[5, 4],
       [4, 1]])

In [57]:
# size vector 10 isort
def size_vector():
    arr = np.random.randint(0,10,10)
    return np.sort(arr)

size_vector()

array([1, 1, 3, 6, 6, 6, 7, 9, 9, 9])

In [60]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)
# np.allclose(A,B)
ac  = np.allclose(A,B)
eq = np.array_equal(A,B)
print(ac)
print(eq)

False
False


In [62]:
# arrays 6x3 and 3x4
arr1 = np.random.randint(0,10,18).reshape(6,3)
arr2 = np.random.randint(0,10,12).reshape(3,4)
print(np.dot(arr1,arr2))

[[ 27  48  33  63]
 [ 30  32  31  18]
 [ 49  37  54  75]
 [ 64  50  69  80]
 [ 66  71  74 104]
 [  7  19  10  29]]


In [65]:
vec = np.random.rand(5)

# Vektorning eng katta elementini 0 ga o'zgartiramiz
max_val = np.max(vec)
max_idx = np.argmax(vec)
vec[max_idx] = 0

print("Asl vektor:", vec)
print("Eng katta qiymat:", max_val)
print("O'zgartirilgan vektor:", vec)


Asl vektor: [0.60675566 0.49510643 0.53126027 0.17967958 0.        ]
Eng katta qiymat: 0.9054205819715466
O'zgartirilgan vektor: [0.60675566 0.49510643 0.53126027 0.17967958 0.        ]


In [66]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [67]:
import numpy as np

a = np.array([1, 2])
b = np.array([4, 5])

print(a > b)   # [False False]
print(a >= b)  # [False False]
print(a < b)   # [ True  True]
print(a <= b)  # [ True  True]


[False False]
[False False]
[ True  True]
[ True  True]


In [69]:
# Massivlar yaratiladi
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

# Umumiy qiymatlarni topish
common_values = np.intersect1d(a, b)

print("Massiv a: ", a)
print("Massiv b: ", b)
print("Umumiy qiymatlar: ", common_values)

Massiv a:  [1 2 3 4 5]
Massiv b:  [3 4 5 6 7]
Umumiy qiymatlar:  [3 4 5]


In [70]:
from numpy.lib.stride_tricks import as_strided
a = np.arange(1, 15)
b = as_strided(a, shape=(11, 4), strides=(a.itemsize, a.itemsize))

print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [87]:
a = [1, 2, 3, 4, 5]
result = [[a[i], 0, 0, 0] for i in range(len(a))]
print(result)


[[1, 0, 0, 0], [2, 0, 0, 0], [3, 0, 0, 0], [4, 0, 0, 0], [5, 0, 0, 0]]


In [89]:
five_dim_array = np.random.rand(5,5,5,5,5)
argmax = np.argmax(five_dim_array)
argmax_0 = np.unravel_index(argmax, five_dim_array.shape)
print(argmax_0)

(3, 3, 2, 3, 0)


In [90]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
# np.sum() funksiyasi orqali
sum_arr = np.sum([a, b, c], axis=0)
print(sum_arr)

# np.add.reduce() funksiyasi orqali
add_reduce_arr = np.add.reduce([a, b, c])
print(add_reduce_arr)


[12 15 18]
[12 15 18]


In [91]:
# Joriy sana va vaqt
today = np.datetime64('today')
print("Joriy sana:", today)

# Ertangi sana
tomorrow = today + np.timedelta64(1, 'D')
print("Ertangi sana:", tomorrow)


Joriy sana: 2023-04-24
Ertangi sana: 2023-04-25


In [92]:
start_date = np.datetime64('2016-01-01')
end_date = np.datetime64('2016-02-01')

dates = np.arange(start_date, end_date, dtype=np.datetime64)

print(dates)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']
