In [86]:
  import numpy as np

In [69]:
def nd_array():
    arr = np.arange(0, 9, 1).reshape(3, 3)
    return arr


nd_array()


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
def sliced_array_2d():
    array = nd_array()
    sliced = array[2, 0:2]
    return sliced


print(sliced_array_2d())

[6 7]


In [80]:
def sliced_array_3d():
    arr3d = np.array([[[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]],

                      [[9, 10, 11],
                       [12, 13, 14],
                       [15, 16, 17]],

                      [[18, 19, 20],
                       [21, 22, 23],
                       [24, 25, 26]]])
    arr = arr3d[1][1:, 0:2]
    return arr


sliced_array_3d()


array([[12, 13],
       [15, 16]])

In [105]:
def boolean_slicing():
    names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
    info = np.array([[5, 6, 1, 1],
                     [9, 1, 1, 1],
                     [7, 7, 4, 2],
                     [1, 5, 1, 9],
                     [9, 9, 4, 5],
                     [7, 5, 9, 6],
                     [5, 3, 7, 4]])
    sliced_info = (names == 'Javohir') | (names == 'Elyor')

    return info[sliced_info]

print(boolean_slicing())

[[7 7 4 2]
 [1 5 1 9]
 [7 5 9 6]
 [5 3 7 4]]
