In [4]:
import numpy as np

In [6]:
A = np.arange(6).reshape(3, 2) # A massiv 0-6, shape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
A.T

array([[0, 2, 4],
       [1, 3, 5]])

In [8]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
A.swapaxes(1, 0) # a massivning T

array([[0, 2, 4],
       [1, 3, 5]])

In [10]:
np.dot(A, A.T) # AA^T hosil bolgan massiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])