In [1]:
import numpy as np

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [9]:
np.log(arr)

/tmp/ipykernel_35544/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [11]:
arr1 = np.random.randn(6)
arr1

array([ 1.58645719, -0.21155134,  1.6756441 , -0.73658891, -0.12901081,
       -0.1867879 ])

In [12]:
qoldiq, butun = np.modf(arr1)
print(qoldiq)
print(butun)

[ 0.58645719 -0.21155134  0.6756441  -0.73658891 -0.12901081 -0.1867879 ]
[ 1. -0.  1. -0. -0. -0.]


In [13]:
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.isnan(arr)

array([False, False, False, False, False, False, False, False, False,
       False])

In [20]:
np.isnan(arr)


array([False, False, False, False, False, False, False, False, False,
       False])

In [21]:
# Binary function

In [22]:
array1 = np.random.randn(6)
array2 = np.random.randn(6)

In [23]:
array2

array([-0.62620661,  0.12771721,  0.98077835, -0.13694896, -0.7779419 ,
       -0.7502874 ])

In [24]:
np.add(array1, array2)

array([-0.15556205, -1.17945579,  1.75347397,  1.51150584, -1.8083482 ,
       -2.25228007])

In [25]:
np.multiply(array1, array2)

array([-0.29472074, -0.16694849,  0.75784313, -0.22575417,  0.80159624,
        1.12692618])

In [26]:
np.maximum(array1, array2)

array([ 0.47064456,  0.12771721,  0.98077835,  1.6484548 , -0.7779419 ,
       -0.7502874 ])